<x-legal-layout title="Terms of Service">

    <p>
        These terms are the agreement between you and {{ config('legal.entity') }}
        ("we", "us") for the use of the Master It app. By creating an account or
        using the app, you agree to them. If you do not agree, do not use the app.
    </p>

    <h2>Who can use Master It</h2>
    <p>
        You must be at least 13 years old, and old enough to form a binding
        contract where you live. You are responsible for your account and for
        keeping your password secure. Tell us promptly if you believe someone else
        has access to it.
    </p>

    <h2>Subscriptions and billing</h2>
    <p>
        Master It is free to use for browsing and following plans from the
        library. Generating a new plan for a goal of your own requires a
        subscription, apart from one free generation per account.
    </p>
    <ul>
        <li>
            Subscriptions are sold and billed by Apple or Google, not by us. Prices
            are shown in the app in your local currency before you buy.
        </li>
        <li>
            Subscriptions renew automatically at the end of each period unless you
            cancel at least 24 hours beforehand. Cancel any time in your device's
            account settings &mdash; we cannot cancel a subscription for you.
        </li>
        <li>
            Refunds are handled by the app store you bought through, under its
            policies. We generally cannot issue them ourselves.
        </li>
        <li>
            Each tier includes a number of plan generations per month, shown on the
            subscription screen and in Settings. The allowance resets monthly and
            unused generations do not carry over.
        </li>
        <li>
            Asking for a plan to be revised uses one generation, because it rewrites
            the plan. Adding a plan from the library does not use any.
        </li>
        <li>
            If a generation fails through a fault on our side, you can retry it
            without using another.
        </li>
    </ul>
    <p>
        We may change prices or what each tier includes. Changes will not affect
        the period you have already paid for, and we will tell you before a change
        takes effect.
    </p>

    <h2>Plans are generated by AI, and are not professional advice</h2>
    <div class="callout">
        <p>
            <strong>
                Master It generates plans automatically. They are suggestions, not
                instructions from a qualified professional, and they can be
                inaccurate, incomplete, or unsafe for your circumstances.
            </strong>
        </p>
        <p>
            Nothing in the app is medical, health, fitness, nutritional, legal,
            financial, or other professional advice. Consult a qualified
            professional before acting on a plan that involves your health, diet,
            physical training, money, or legal position &mdash; especially if you
            have a medical condition, are pregnant, are injured, or are starting
            something physically demanding.
        </p>
        <p>You follow a plan at your own risk, and you are responsible for judging whether it is appropriate and safe for you.</p>
    </div>
    <p>
        The same applies to suggested reading and videos: they come from third
        parties, we do not review or endorse them, and we are not responsible for
        their content or accuracy.
    </p>

    <h2>What you may not use Master It for</h2>
    <p>The app declines to generate plans for goals that are:</p>
    <ul>
        <li>Illegal &mdash; plans that would walk someone through committing a crime.</li>
        <li>Sexual in nature, or involving the sexual exploitation of minors.</li>
        <li>Centred on gore, cruelty, or self-harm rather than a constructive activity.</li>
    </ul>
    <p>You also agree not to:</p>
    <ul>
        <li>Break into, disrupt, overload, or probe the service or its infrastructure.</li>
        <li>Use automated means to create accounts or generate plans at scale.</li>
        <li>Work around generation allowances, subscription checks, or rate limits.</li>
        <li>Resell or commercially redistribute plan content generated by the app.</li>
        <li>Use the app to harass anyone, or to infringe anyone's rights.</li>
    </ul>

    <h2>Your content</h2>
    <p>
        What you write &mdash; your goals, notes, and feedback &mdash; stays yours.
        You grant us the limited licence needed to run the service: to store your
        content, to send the parts described in the
        <a href="/privacy">Privacy Policy</a> to the providers that generate your
        plan, and, where you deliberately share a plan, to show it to the people
        you share it with.
    </p>
    <p>
        This licence exists only to operate the app. It ends when you delete the
        content or your account, apart from copies other people made of a plan you
        chose to share.
    </p>
    <p>
        If you send us feedback or suggestions about the app itself, we may use
        them without obligation to you.
    </p>

    <h2>Availability and changes</h2>
    <p>
        We may change, suspend, or discontinue any part of the app. We aim to keep
        it running but do not promise uninterrupted or error-free service, and
        parts of it depend on third parties that can fail or change independently
        of us.
    </p>
    <p>
        You may stop using the app and delete your account at any time. We may
        suspend or terminate an account that breaches these terms, or where we are
        required to. If we terminate your account without cause while you have
        paid time remaining, you may request a pro-rata refund through your app
        store.
    </p>

    <h2>Disclaimers</h2>
    <p>
        The app is provided "as is" and "as available", without warranties of any
        kind, whether express or implied, including any implied warranties of
        merchantability, fitness for a particular purpose, accuracy, or
        non-infringement, to the fullest extent the law allows.
    </p>

    <h2>Limitation of liability</h2>
    <p>
        To the fullest extent permitted by law, we are not liable for indirect,
        incidental, special, consequential, or punitive damages, nor for lost
        profits, lost data, or loss arising from your reliance on a generated
        plan. Our total liability for any claim relating to the app is limited to
        the greater of the amount you paid us in the twelve months before the
        claim, or twenty-five US dollars.
    </p>
    <p>
        Some jurisdictions do not allow certain exclusions or limitations, so parts
        of the two sections above may not apply to you. Nothing here limits
        liability that cannot lawfully be limited.
    </p>

    <h2>Governing law</h2>
    <p>
        These terms are governed by the laws of {{ config('legal.jurisdiction') }},
        without regard to its conflict-of-laws rules. You and we agree that the
        state and federal courts located there have exclusive jurisdiction over
        any dispute, except that either of us may seek injunctive relief in any
        competent court, and you may bring a qualifying claim in small-claims
        court.
    </p>

    <h2>Changes to these terms</h2>
    <p>
        We may update these terms. The date at the top of this page shows when
        they last changed, and material changes will be brought to your attention
        in the app. Continuing to use Master It after a change means you accept
        the updated terms.
    </p>

    <h2>The whole agreement</h2>
    <p>
        These terms, together with the <a href="/privacy">Privacy Policy</a>, are
        the entire agreement between you and us about the app. If any provision is
        found unenforceable, the rest stays in force. Our not enforcing a
        provision is not a waiver of it.
    </p>

</x-legal-layout>
